name: g2g
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - pip
  pip: 
    - cython==3.0.11
    - leven==1.0.4
    - ortools==9.10.4067
    - optbinning==0.20.0
    - scikit-learn==1.2
    - git+https://github.com/Teichlab/Genes2Genes.git@main